os:
  - linux
  - osx

language: c
before_install: |
  which apt-get && curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  which apt-get && sudo apt-get -q update
  which brew && brew tap manastech/crystal
  which brew && brew install crystal

install: |
  sudo apt-get install crystal

before_script:
  - ./script/setup-test-db.sh

script:
  - crystal spec
